name: Escapecraft
version: ${project.version}
main: escapecraft.escapecraft.Escapecraft
api-version: 1.16
commands:
  disable:
    description: disable chat
    usage: /<command>
    permission: "3"
  enable:
    description: enable chat
    usage: /<command>
    permission: "3"
  quest:
    description: do questions i guess
    usage: /<command>
    permission: "3"