name: Escapecraft
version: ${project.version}
main: escapecraft.escapecraft.Escapecraft
api-version: 1.16
commands:
  test:
    description: idfk, something i guess?
    usage: /<command>
    permission: "3"